services:

  db:
    image: postgres:15-alpine
    container_name: healenium_db
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: healenium_password

    volumes:
      - ./hlm-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healenium_user -d healenium"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

    networks:
      - healenium-network

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.6
    container_name: selector-imitator
    ports:
      - "8000:8000"

    restart: always

    networks:
      - healenium-network

  healenium:
    image: healenium/hlm-backend:3.5.1
    container_name: healenium_backend

    depends_on:
      db:
        condition: service_healthy

      selector-imitator:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/healenium
      SPRING_DATASOURCE_USERNAME: healenium_user
      SPRING_DATASOURCE_PASSWORD: healenium_password
      SERVER_PORT: 7878

      RECOVERY_TRIES: 1
      SCORE_CAP: "0.6"
      HEAL_ENABLED: "true"

      HLM_IMITATOR_HOST: selector-imitator
      HLM_IMITATOR_PORT: 8000

    ports:
      - "7878:7878"

    restart: always

    networks:
      - healenium-network

networks:
  healenium-network:
    driver: bridge