services:

  db:
    image: postgres:15-alpine
    container_name: healenium_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: healenium_password
    networks:
      - healenium-network
    restart: always

  healenium:
    image: healenium/hlm-backend:3.5.1
    container_name: healenium_backend
    ports:
      - "7878:7878"
    depends_on:
      - db
      - selector-imitator
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/healenium
      SPRING_DATASOURCE_USERNAME: healenium_user
      SPRING_DATASOURCE_PASSWORD: healenium_password
      SERVER_PORT: 7878
    networks:
      - healenium-network
    restart: always

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.6
    container_name: selector-imitator
    ports:
      - "8000:8000"
    networks:
      - healenium-network
    restart: always

networks:
  healenium-network:
    driver: bridge